export const assets = {
  home: {
    hero: {
      avatarSmile: require("@images/home/hero/1702365021591.jpg"),
      dribble: require("@images/home/hero/dribble.webp"),
      github: require("@images/home/hero/github.webp"),
      instagram: require("@images/home/hero/instagram.webp"),
      linkedin: require("@images/home/hero/linkedin.webp"),
      quadrilateral: require("@images/home/hero/quadrilateral.webp"),
      triangle: require("@images/home/hero/triangle.webp"),
      twistedTorus: require("@images/home/hero/twisted-torus.webp"),
      zigZag: require("@images/home/hero/zig-zag.webp"),
    },
    letsConnect: {
      avatarBigSmile: require("@images/home/letsConnect/avatar-big-smile.webp"),
      dribble: require("@images/home/letsConnect/dribble.webp"),
      github: require("@images/home/letsConnect/github.webp"),
      gmail: require("@images/home/letsConnect/gmail.webp"),
      instagram: require("@images/home/letsConnect/instagram.webp"),
      linkedin: require("@images/home/letsConnect/linkedin.webp"),
      medium: require("@images/home/letsConnect/medium.webp"),
      twitter: require("@images/home/letsConnect/twitter.webp"),
    },
    myLatestProject: {
      figma: require("@images/home/myLatestProject/figma.webp"),
      rocket: require("@images/home/myLatestProject/rocket.webp"),
      suitcase: require("@images/home/myLatestProject/suitcase.webp"),
      projects: {
        portfolioWebsite: require("@images/home/myLatestProject/projects/portfolio-website.webp"),
        parkinsonDisease: require("@images/projects/_01/1.png"),
        customerChurn: require("@images/projects/_02/1.png"),
        bank: require("@images/projects/_03/1.png"),
        clinicalTrial: require("@images/projects/_04/1.png"),
        carRental: require("@images/projects/_05/1.png"),
        audirea: require("@images/projects/_06/1.png"), 
        flowerExchange: require("@images/projects/_07/1.png"),
        happinessReport: require("@images/projects/_08/1.png"),
      },
    },
    quote: {
      bulb: require("@images/home/quote/bulb.webp"),
      heart: require("@images/home/quote/heart.webp"),
      paintKit: require("@images/home/quote/paint-kit.webp"),
      teaCup: require("@images/home/quote/tea-cup.webp"),
    },
    technologyStack: {
      expo: require("@images/home/technologyStack/expo.webp"),
      expressJs: require("@images/home/technologyStack/express-js.webp"),
      javascript: require("@images/home/technologyStack/javascript.webp"),
      laravel: require("@images/home/technologyStack/laravel.webp"),
      nextJs: require("@images/home/technologyStack/next-js.webp"),
      planetScale: require("@images/home/technologyStack/planet-scale.webp"),
      prisma: require("@images/home/technologyStack/prisma.webp"),
      reactJs: require("@images/home/technologyStack/react-js.webp"),
      reactNative: require("@images/home/technologyStack/react-native.webp"),
      tailwindCss: require("@images/home/technologyStack/tailwindcss.webp"),
      typescript: require("@images/home/technologyStack/typescript.webp"),
    },
    interests: {
      ml: require("@images/home/interests/ml-icon.png"),
      nlp: require("@images/home/interests/nlp-icon.png"),
      bigdata: require("@images/home/interests/bigdata-icon.png"),
      se: require("@images/home/interests/se-icon.png"),
      ds: require("@images/home/interests/ds-icon.png"),
      sd: require("@images/home/interests/sd-icon.png"),
      wd: require("@images/home/interests/wd-icon.png"),
      reactJs: require("@images/home/technologyStack/react-js.webp"),
      reactNative: require("@images/home/technologyStack/react-native.webp"),
      tailwindCss: require("@images/home/technologyStack/tailwindcss.webp"),
      typescript: require("@images/home/technologyStack/typescript.webp"),
    },
    blogs: {
      blog1: require("@images/blogs/_01/1.png"),
      blog2: require("@images/blogs/_02/1.png"),
      blog3: require("@images/blogs/_03/1.png"),
      blog4: require("@images/blogs/_04/1.png"),
      blog5: require("@images/blogs/_05/1.png"),
      
    }
  },
};
